"""`emblem` command line: every capability of the platform is runnable and demonstrable from here."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from emblem import db as dbmod
from emblem.architecture import platform, sor
from emblem.catalog import audit, lineage
from emblem.contracts import load_contracts
from emblem.demo import AS_OF, build_demo
from emblem.governance import vendor
from emblem.ops import incidents as inc
from emblem.plan import plan as planmod
from emblem.quality import checks, reconcile
from emblem.reporting import dashboard, semantic_model, showcase
from emblem.security import rbac, retention

DEFAULT_DB = "build/emblem.duckdb"


def _p(obj: Any) -> None:
    print(json.dumps(obj, indent=2, default=str))


def _open(a: argparse.Namespace) -> Any:
    Path(a.db).parent.mkdir(parents=True, exist_ok=True)
    return dbmod.connect(a.db)


def _need_data(con: Any) -> None:
    if con.execute("SELECT count(*) FROM meta.dq_results").fetchone()[0] == 0:
        raise SystemExit("No data yet. Run: uv run emblem demo")


def cmd_demo(a: argparse.Namespace) -> None:
    Path(a.db).unlink(missing_ok=True)
    con = _open(a)
    r = build_demo(con, a.scale)
    ver = planmod.verify(planmod.Ctx(con, as_of=AS_OF))
    out = Path(a.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(dashboard.render(showcase.build_snapshot(con, AS_OF, ver)), encoding="utf-8")
    print(
        f"quality {r['checks']['passed']}/{r['checks']['total']} passing | recon breaks {r['recon_breaks']} | open incidents {r['incidents']['open']}"
    )
    print(f"90-day milestones verified: {sum(v['ok'] for v in ver)}/{len(ver)}")
    print(f"dashboard: {out}   (or: uv run emblem serve -> http://127.0.0.1:8000)")


def cmd_run(a: argparse.Namespace) -> None:
    con = _open(a)
    from emblem.pipelines.runner import run_batch

    for b in [int(x) for x in a.batches.split(",")]:
        r = run_batch(con, b, scale=a.scale)
        print(
            f"batch {b}: bronze+{sum(s['inserted'] for s in r['bronze'])} rows, gold tables {len(r['gold'])}, companies {r['mdm']['companies']}"
        )


def cmd_audit(a: argparse.Namespace) -> None:
    f = audit.findings()
    if a.baseline:
        return _p(audit.baseline())
    if a.json:
        return _p(f)
    for x in f:
        print(f"{x['id']} [{x['severity']:<8}] {x['category']:<19} {x['subject']:<10} {x['description']}")


def _with_data(a: argparse.Namespace) -> Any:
    con = _open(a)
    _need_data(con)
    return con


def cmd_quality(a: argparse.Namespace) -> None:
    s = checks.summarise(checks.run_checks(_with_data(a), AS_OF, "cli"))
    _p({k: s[k] for k in ("total", "passed", "failed", "score", "by_dimension")})
    for f in s["failures"]:
        print(f"FAIL {f['check_id']}: {f['detail']}")


def cmd_reconcile(a: argparse.Namespace) -> None:
    _p([r.as_dict() for r in reconcile.reconcile(_with_data(a))])


def cmd_incidents(a: argparse.Namespace) -> None:
    for i in inc.list_incidents(_with_data(a), "open"):
        print(
            f"{i['incident_id']} {i['severity']} {i['domain']:<10} owner={i['owner']:<10} {i['title'][:90]}"
        )


def cmd_plan(a: argparse.Namespace) -> None:
    if a.action == "render":
        Path("docs/90-DAY-PLAN.md").write_text(planmod.render_markdown(), encoding="utf-8")
        return print("wrote docs/90-DAY-PLAN.md")
    if a.action == "roadmap":
        return _p(planmod.roadmap())
    if a.action == "budget":
        return _p(planmod.budget())
    res = planmod.verify(planmod.Ctx(_with_data(a), as_of=AS_OF))
    for r in res:
        print(
            f"{'PASS' if r['ok'] else 'FAIL'} {r['id']} days {r['days']:<6} {r['title'][:60]:<60} | {r['evidence']}"
        )
    raise SystemExit(0 if all(r["ok"] for r in res) else 1)


def cmd_docs(a: argparse.Namespace) -> None:
    con = _with_data(a)
    g = lineage.build()
    Path("docs/lineage.md").write_text(
        "# Lineage (generated)\n\nGenerated by `uv run emblem docs` from contracts and SQL `ref()` calls.\n\n```mermaid\n"
        + lineage.mermaid(g)
        + "\n```\n",
        encoding="utf-8",
    )
    Path("docs/90-DAY-PLAN.md").write_text(planmod.render_markdown(), encoding="utf-8")
    t = [
        "# JD compliance matrix (generated)",
        "",
        "| Section | Requirement | Evidence | Demo |",
        "|---|---|---|---|",
    ]
    t += [
        f"| {x['section']} | {x['requirement']} | {' '.join(f'`{p}`' for p in x['evidence'].split(';'))} | `{x['demo']}` |"
        for x in showcase.traceability()
    ]
    Path("docs/JD-COMPLIANCE.md").write_text("\n".join(t) + "\n", encoding="utf-8")
    Path("docs/powerbi").mkdir(exist_ok=True)
    Path("docs/powerbi/model.bim").write_text(
        semantic_model.to_json(semantic_model.build(con)), encoding="utf-8"
    )
    print("wrote docs/lineage.md docs/90-DAY-PLAN.md docs/JD-COMPLIANCE.md docs/powerbi/model.bim")


def cmd_serve(a: argparse.Namespace) -> None:
    import uvicorn

    from emblem.api.app import create_app

    uvicorn.run(create_app(a.db), host=a.host, port=a.port, log_level="info")


def cmd_lakehouse(a: argparse.Namespace) -> None:
    from emblem.pipelines.lakehouse import export_gold

    _p(export_gold(_with_data(a), Path(a.out)))


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog="emblem", description="World Emblem data foundation showcase")
    ap.add_argument("--db", default=DEFAULT_DB)
    sub = ap.add_subparsers(dest="cmd", required=True)

    def add(name: str, fn: Any, **kw: Any) -> argparse.ArgumentParser:
        p = sub.add_parser(name)
        p.set_defaults(fn=fn)
        for k, v in kw.items():
            p.add_argument(f"--{k}", default=v) if not isinstance(v, bool) else p.add_argument(
                f"--{k}", action="store_true"
            )
        return p

    d = add("demo", cmd_demo, out="build/report.html")
    d.add_argument("--scale", type=float, default=1.0)
    r = add("run", cmd_run, batches="1,2,3")
    r.add_argument("--scale", type=float, default=1.0)
    add("audit", cmd_audit, baseline=False, json=False)
    add("quality", cmd_quality)
    add("reconcile", cmd_reconcile)
    add("incidents", cmd_incidents)
    pl = add("plan", cmd_plan)
    pl.add_argument("action", choices=["render", "verify", "roadmap", "budget"])
    add("docs", cmd_docs)
    s = add("serve", cmd_serve, host="127.0.0.1")
    s.add_argument("--port", type=int, default=8000)
    add("lakehouse", cmd_lakehouse, out="build/lakehouse")
    sub.add_parser("contracts").set_defaults(
        fn=lambda a: _p(
            {
                k: {
                    "owner": c.owner,
                    "pk": c.pk,
                    "columns": len(c.columns),
                    "freshness_h": c.freshness_hours,
                    "retention_d": c.retention_days,
                }
                for k, c in load_contracts().items()
            }
        )
    )
    sub.add_parser("sor").set_defaults(
        fn=lambda a: _p(
            {
                "matrix": sor.matrix_rows(),
                "conflicts": sor.conflicting_writers(audit.load_inventory()["integrations"]),
            }
        )
    )
    sub.add_parser("platform").set_defaults(fn=lambda a: _p(platform.recommendation()))
    sub.add_parser("vendors").set_defaults(fn=lambda a: _p(vendor.evaluate()))
    sub.add_parser("governance").set_defaults(
        fn=lambda a: _p(
            {"roles": rbac.role_names(), "retention_dry_run": retention.enforce(_with_data(a), AS_OF)}
        )
    )
    sub.add_parser("semantic").set_defaults(
        fn=lambda a: print(semantic_model.to_json(semantic_model.build(_with_data(a))))
    )
    lg = sub.add_parser("lineage")
    lg.add_argument("--json", action="store_true")
    lg.set_defaults(fn=lambda a: _p(lineage.build()) if a.json else print(lineage.mermaid(lineage.build())))
    args = ap.parse_args(argv)
    args.fn(args)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
