-- GENERATED by tools/sync_dbt.py from src/emblem/data/sql/gold. Do not edit.
-- Common model: location (plants and warehouses). Authoritative: reference data owned by Operations.
SELECT location_code AS location_key, location_name, location_type, state FROM {{ source('ref', 'locations') }}
