-- GENERATED by tools/sync_dbt.py from src/emblem/data/sql/gold. Do not edit.
-- Common model: company (golden record). Survivorship follows architecture/system_of_record.yaml:
-- name+financials: Business Central > HubSpot > BigCommerce > Optimizely; ownership+lifecycle: HubSpot.
SELECT x.company_key,
  coalesce(min(c.name) FILTER (WHERE x.source = 'bc'), min(h.name) FILTER (WHERE x.source = 'hs'),
           min(g.company) FILTER (WHERE x.source = 'bg'), min(q.company_name) FILTER (WHERE x.source = 'opti')) AS company_name,
  min(c.city) FILTER (WHERE x.source = 'bc') AS billing_city,
  min(c.state) FILTER (WHERE x.source = 'bc') AS billing_state,
  min(c.credit_limit) FILTER (WHERE x.source = 'bc') AS credit_limit,
  min(c.tax_id) FILTER (WHERE x.source = 'bc') AS tax_id,
  min(h.owner_email) FILTER (WHERE x.source = 'hs') AS account_owner,
  min(h.lifecycle_stage) FILTER (WHERE x.source = 'hs') AS lifecycle_stage,
  string_agg(DISTINCT c.no, ',') FILTER (WHERE x.source = 'bc') AS bc_customer_nos,
  count(DISTINCT x.source || ':' || x.source_id) AS source_record_count,
  string_agg(DISTINCT x.source, ',') AS source_systems,
  count(DISTINCT c.no) > 1 AS duplicate_in_erp
FROM {{ source('silver', 'xref_company') }} x
LEFT JOIN {{ source('silver', 'stg_bc__customers') }} c ON x.source = 'bc' AND c.no = x.source_id
LEFT JOIN {{ source('silver', 'stg_hs__companies') }} h ON x.source = 'hs' AND h.id = x.source_id
LEFT JOIN {{ source('silver', 'stg_bg__customers') }} g ON x.source = 'bg' AND g.id = x.source_id
LEFT JOIN {{ source('silver', 'stg_opti__quotes') }} q ON x.source = 'opti' AND q.id = x.source_id
GROUP BY x.company_key
