-- GENERATED by tools/sync_dbt.py from src/emblem/data/sql/gold. Do not edit.
-- Exception queue: web orders with no Business Central counterpart (fix at the integration, not the report).
SELECT g.id AS web_order_id, g.date_created, g.total_inc_tax, g.status, g.customer_id
FROM {{ source('silver', 'stg_bg__orders') }} g
WHERE NOT EXISTS (SELECT 1 FROM {{ source('silver', 'stg_bc__sales_orders') }} o WHERE o.external_doc_no = 'BG-' || g.id)
