-- GENERATED by tools/sync_dbt.py from src/emblem/data/sql/gold. Do not edit.
SELECT id AS spend_key, spend_date, platform, campaign, spend, clicks, impressions FROM {{ source('silver', 'stg_mkt__ad_spend') }}
