"""Generate dbt models from the canonical gold SQL so the two can never drift (CI runs `--check`)."""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src" / "emblem" / "data" / "sql" / "gold"
OUT = ROOT / "dbt_project" / "models"
REF = re.compile(r"\{\{\s*ref\('([a-z0-9_]+)'\)\s*\}\}")
REF_TABLES = {"locations", "fx_rates"}
GOLD = {p.stem for p in SRC.glob("*.sql")}


def convert(sql: str) -> str:
    def sub(m: re.Match[str]) -> str:
        n = m.group(1)
        if n in GOLD:
            return m.group(0)
        return "{{ source('ref', '%s') }}" % n if n in REF_TABLES else "{{ source('silver', '%s') }}" % n

    return "-- GENERATED by tools/sync_dbt.py from src/emblem/data/sql/gold. Do not edit.\n" + REF.sub(
        sub, sql
    )


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    stale = []
    for p in sorted(SRC.glob("*.sql")):
        target, want = OUT / p.name, convert(p.read_text())
        if "--check" in sys.argv:
            if not target.exists() or target.read_text() != want:
                stale.append(p.name)
        else:
            target.write_text(want)
    if stale:
        print("dbt models out of sync:", ", ".join(stale))
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
